# Generated by Django 3.2.10 on 2022-11-09 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0009_user_is_placed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Homepage.course'),
        ),
    ]
