# Generated by Django 3.2.10 on 2022-11-09 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0010_alter_user_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_name', to='Homepage.departments'),
        ),
    ]
