# Generated by Django 3.2.10 on 2022-11-04 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_auto_20221104_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='course_name',
        ),
        migrations.AddField(
            model_name='user',
            name='course_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Homepage.course'),
            preserve_default=False,
        ),
    ]
