# Generated by Django 3.2.10 on 2022-11-04 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0003_auto_20221104_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department_name',
        ),
        migrations.AddField(
            model_name='user',
            name='department_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='department_name', to='Homepage.departments'),
            preserve_default=False,
        ),
    ]
