# Generated by Django 3.2.10 on 2022-11-06 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0005_announcements'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='responses',
            name='status',
            field=models.CharField(blank=True, choices=[(1, 'Applied'), (2, 'Processing'), (3, 'Shortlisted'), (4, 'Rejected'), (5, 'Selected')], max_length=50, null=True),
        ),
    ]
