# Generated by Django 3.2.10 on 2022-11-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0006_auto_20221106_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='status',
            field=models.CharField(choices=[(1, 'Applied'), (2, 'Processing'), (3, 'Shortlisted'), (4, 'Rejected'), (5, 'Selected')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
