# Generated by Django 3.2.10 on 2022-11-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0007_alter_responses_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Applied'), (2, 'Processing'), (3, 'Shortlisted'), (4, 'Rejected'), (5, 'Selected')], null=True),
        ),
    ]
