# Generated by Django 3.2.10 on 2022-11-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0008_alter_responses_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_placed',
            field=models.BooleanField(default=False),
        ),
    ]
